name: qc_test

on:
  push :
  schedule :
    - cron : '55 23 * * *'

jobs:
  build:
    runs-on: windows-latest
    steps:
    
    #引用外部Action,拉取代码仓库到虚拟机工作目录
    - name : pull Badminton-hall
      run: |
        git init
        git pull https://github.com/Milleroh/Badminton-hall.git
        dir
        
    # 查看目录情况
    - name: show dir
      run: |
        dir
    
    # 搭建环境 pyhton
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    # 安装 selenium
    - name : pip install selenium
      run: |
        pip install selenium
        
    # 安装 msedge.selenium_tools
    - name : pip install msedge.selenium_tools
      run: |
        pip install msedge.selenium_tools
        
    #添加路径
    - name : export_PATH
      run: |
        setx /M path "%path%;.\MicrosoftWebDriver.exe"
      
    # 运行
    - name : qc_start
      run: |
        python qc.py
